name: mvp_social_quest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  # Location & maps
  geolocator: ^14.0.0
  geocoding: ^3.0.0

  # Persistence & cache
  shared_preferences: ^2.5.3
  path_provider: ^2.1.2

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_crashlytics: ^4.3.5

  # Auth
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1

  # UI & i18n
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  intl: ^0.20.2
  fl_chart: ^0.71.0
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.1.3
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Routing
  go_router: ^15.1.1
  flutter_riverpod: ^2.6.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
