name: mvp_social_quest
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # Location & maps
  geolocator: ^14.0.0
  geocoding: ^3.0.0

  # Persistence & cache
  shared_preferences: ^2.5.3
  path_provider: ^2.1.2

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_crashlytics: ^4.3.5

  # Auth
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1

  # UI & i18n
  intl: ^0.19.0
  fl_chart: ^0.71.0
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  path_provider: ^2.1.2
  firebase_crashlytics: ^4.3.5
  table_calendar: ^3.1.3
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Charts & calendar
  fl_chart: ^0.71.0
  table_calendar: ^3.1.3

  # Images & rating
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/placeholder.jpg
<<<<<<< HEAD
=======

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
>>>>>>> c7b59b93ad14c68d21bc22442bb0e7c87dcc3314
