// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATTaxfa_cwZc7eWCrCKjA7DZS9hxbp1hU',
    appId: '1:326489596162:web:d5fc6824e58f962524621b',
    messagingSenderId: '326489596162',
    projectId: 'red-uc-7afda',
    authDomain: 'red-uc-7afda.firebaseapp.com',
    storageBucket: 'red-uc-7afda.firebasestorage.app',
    measurementId: 'G-RN5FL162DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnntEB1EmgfIe-OkhSY_sqeo0wC1mFkMg',
    appId: '1:326489596162:android:641f6274530633e724621b',
    messagingSenderId: '326489596162',
    projectId: 'red-uc-7afda',
    storageBucket: 'red-uc-7afda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyButicQp66BGXeJAAV0hOI1gqzIqxlrWxM',
    appId: '1:326489596162:ios:291def4e187f65a924621b',
    messagingSenderId: '326489596162',
    projectId: 'red-uc-7afda',
    storageBucket: 'red-uc-7afda.firebasestorage.app',
    iosBundleId: 'com.example.mvpSocialQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyButicQp66BGXeJAAV0hOI1gqzIqxlrWxM',
    appId: '1:326489596162:ios:291def4e187f65a924621b',
    messagingSenderId: '326489596162',
    projectId: 'red-uc-7afda',
    storageBucket: 'red-uc-7afda.firebasestorage.app',
    iosBundleId: 'com.example.mvpSocialQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATTaxfa_cwZc7eWCrCKjA7DZS9hxbp1hU',
    appId: '1:326489596162:web:acd52986f810d2ec24621b',
    messagingSenderId: '326489596162',
    projectId: 'red-uc-7afda',
    authDomain: 'red-uc-7afda.firebaseapp.com',
    storageBucket: 'red-uc-7afda.firebasestorage.app',
    measurementId: 'G-Q40HH59HW3',
  );
}
